In [572]:
import pandas as pd
import requests
import time
from sklearn.model_selection import train_test_split,cross_val_score

# SCRAPE DATA

In [547]:
import requests
import requests.auth
client_auth = requests.auth.HTTPBasicAuth('PMd9sKprwheUIQ', 'k7MAvz4NDVQKOgfqv41Rqf3FCUo')
post_data = {"grant_type": "password", "username": "cimga", "password": "cimga5823494"}
headers = {"User-Agent": "ChangeMeClient/0.1 by cimga"}
response = requests.post("https://www.reddit.com/api/v1/access_token", auth=client_auth, data=post_data,
                         headers=headers)
response.json()


In [548]:
headers = {"Authorization": "bearer 259091767874-Ivv2hkMm_dmvMcCLrSGxSmFLKfk", "User-Agent": "ChangeMeClient/0.1 by cimga"}
response = requests.get("https://oauth.reddit.com/api/v1/me", headers=headers)
response.json()

In [549]:
import praw

reddit = praw.Reddit(client_id='PMd9sKprwheUIQ',
                     client_secret='k7MAvz4NDVQKOgfqv41Rqf3FCUo',
                     user_agent='ChangeMeClient/0.1 by cimga',
                    
                    )

In [550]:
print(reddit.read_only)

In [551]:
l=[]
for i in reddit.subreddit('travel').hot(limit=3000):
    l.append([i.id,i.subreddit,i.title,i.selftext])
    
for i in reddit.subreddit('geography').hot(limit=3000):
    l.append([i.id,i.subreddit,i.title,i.selftext])
    
l[0:2]

In [552]:
columns=['id','subreddit','title','selftext']
df=pd.DataFrame(l,columns=columns)
df[0:5]

In [553]:
df.to_csv('./first_data',index=False)

In [573]:
df=pd.read_csv('./first_data')

In [574]:
df.shape

(1968, 5)

In [575]:
df.head(2)

id subreddit                                              title  \
0  b9bzar    travel    r/travel Topic of the Week: 'Lifestyle Choices'   
1  b9u8w8    travel  Just outside Marrakesh, Morocco (those are res...   

                                            selftext  \
0  Hey travellers!\n \nIn this weekly community d...   
1                                                NaN   

                                              merged  
0  r/travel Topic of the Week: 'Lifestyle Choices...  
1  Just outside Marrakesh, Morocco (those are res...

In [576]:
df.isnull().sum()

id             0
subreddit      0
title          0
selftext     905
merged         0
dtype: int64

In [577]:
df.fillna('unknown',inplace=True)
df.head(3)

id subreddit                                              title  \
0  b9bzar    travel    r/travel Topic of the Week: 'Lifestyle Choices'   
1  b9u8w8    travel  Just outside Marrakesh, Morocco (those are res...   
2  b9onlo    travel                 Angels Landing- Zion National Park   

                                            selftext  \
0  Hey travellers!\n \nIn this weekly community d...   
1                                            unknown   
2                                            unknown   

                                              merged  
0  r/travel Topic of the Week: 'Lifestyle Choices...  
1  Just outside Marrakesh, Morocco (those are res...  
2         Angels Landing- Zion National Park unknown

In [578]:
df[df['selftext']=='unknown'].groupby('subreddit').count()

id  title  selftext  merged
subreddit                              
geography  720    720       720     720
travel     185    185       185     185

In [579]:
720/905

0.7955801104972375

In [580]:
#convert to binary our y value
df['subreddit']=df['subreddit'].replace({'travel':1,'geography':0}) 

# FEATURES

In [581]:
df['merged']=df['title'] +' '+ df['selftext']
df.head(3)

id  subreddit                                              title  \
0  b9bzar          1    r/travel Topic of the Week: 'Lifestyle Choices'   
1  b9u8w8          1  Just outside Marrakesh, Morocco (those are res...   
2  b9onlo          1                 Angels Landing- Zion National Park   

                                            selftext  \
0  Hey travellers!\n \nIn this weekly community d...   
1                                            unknown   
2                                            unknown   

                                              merged  
0  r/travel Topic of the Week: 'Lifestyle Choices...  
1  Just outside Marrakesh, Morocco (those are res...  
2         Angels Landing- Zion National Park unknown

# MODELS

In [582]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer,HashingVectorizer
from sklearn.naive_bayes import MultinomialNB,BernoulliNB,GaussianNB
from sklearn.metrics import confusion_matrix
from sklearn.grid_search import GridSearchCV
from sklearn.pipeline import Pipeline
# from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

from sklearn.linear_model import LogisticRegression

### Grid Search

In [583]:
X=df['merged'] # in series form NOT dataframe!
y=df['subreddit']

X_train, X_test, y_train, y_test=train_test_split(X,y, test_size=0.33, random_state=42, stratify=y)

In [584]:
pipe=Pipeline( [ ('vec',CountVectorizer()),
                  ('model',MultinomialNB())
               ])

pipe_params={ 
    'vec__stop_words': [None, 'english'],
    'vec__max_features': [30,250,300,1000,5000,None],
    'vec__ngram_range': [(1,1), (1,2)]
    
#     'vec__token_pattern':['(?u)\\b\\w\\w+\\b']
#     prefixes must be the same with above mentioned 
#     vector and model. otherwise it deosnt recognize.
#         'stop_wrods':[None,'english'],
#         'max_features':[2000],
#         'n_gram':[(1,1),(1,2)]
                }

gs=GridSearchCV(pipe,param_grid=pipe_params,cv=3)
gs.fit(X_train, y_train)
print('gs.best score(cros_val_score):',gs.best_score_)
feeder=pipe.named_steps
best_paramaters=gs.best_params_
best_paramaters

gs.best score(cros_val_score): 0.9165402124430956


{'vec__max_features': 5000,
 'vec__ngram_range': (1, 2),
 'vec__stop_words': 'english'}

In [586]:
#this code supposed to work but didnt! maybe need to update the sklearn
#pd.DataFrame(gs.cv_results_).T

### Split for Train and Test

In [587]:
X=df[['merged']]  # dataframe format
y=df['subreddit']
X.head(5)

merged
0  r/travel Topic of the Week: 'Lifestyle Choices...
1  Just outside Marrakesh, Morocco (those are res...
2         Angels Landing- Zion National Park unknown
3  The ancient village of Misfat Al Abriyeen in t...
4  Fishing boat in Ha Long Bay at dawn. Pearl oys...

In [588]:
# Baseline is % 51
y.value_counts(1)

1    0.505589
0    0.494411
Name: subreddit, dtype: float64

In [589]:
X_train, X_test, y_train, y_test=train_test_split(X,y, test_size=0.33, random_state=42, stratify=y)

## 1- BAYES CLASSIFIER

### a-CountVectorizer

Grid Search Output:
- {'vec__max_features': 5000,
 'vec__ngram_range': (1, 2),
 'vec__stop_words': 'english'}

if we use the __grid search__ output: max_feature=2500, stop_words=None, ngram_range=(1, 1)
- cross val score: 0.902
- train score    : 0.943
- test score     : __0.430__

If we enter parameters __intuitively__ : max_feature=1500, stop_words=None, ngram_range=(1, 1)
- cross val score: 0.897
- train score    : 0.927
- test score     : __0.620__

If we enter parameters __intuitively__ : max_feature=1500, stop_words='english', ngram_range=(1, 1)
- cross val score: 0.872
- train score    : 0.914
- test score     : __0.524__

**_So Grid Search is not the best solution always ????_**



- best_paramaters <br>
{'vec__max_features': 5000,
 'vec__ngram_range': (1, 2),
 'vec__stop_words': 'english'}

In [590]:
cvec=CountVectorizer(   max_features=250,
                        ngram_range=(1, 1),
                        stop_words=None,
#                     tokenizer=None,
#                     token_pattern='(?u)\\b\\w\\w+\\b'
        )

In [591]:
X_train_cvec=pd.DataFrame(cvec.fit_transform(X_train['merged']).todense(), columns=cvec.get_feature_names())
X_train_cvec.head()

# what is the aim of the TODENSE(). if i dont write it then code doesnt work, why???????????????????

10  able  about  advance  advice  after  airport  all  also  am  ...   \
0   0     0      0        0       0      1        0    0     0   1  ...    
1   0     0      0        0       1      0        0    0     0   0  ...    
2   0     0      0        0       0      0        0    0     0   0  ...    
3   0     0      0        3       0      1        0    0     0   0  ...    
4   0     0      2        0       1      3        0    0     0   0  ...    

   work  world  worth  would  www  x200b  year  years  you  your  
0     0      0      0      0    0      0     0      0    1     0  
1     0      0      0      1    0      0     0      0    3     1  
2     0      0      0      0    0      0     0      0    0     0  
3     0      0      0      0    0      0     0      0    0     0  
4     0      0      0      1    0      0     0      0    2     3  

[5 rows x 250 columns]

In [592]:
X_train_cvec.shape

(1318, 250)

In [593]:
X_test_cvec=pd.DataFrame(cvec.fit_transform(X_test['merged']).todense(),columns=cvec.get_feature_names())
X_test_cvec.shape

(650, 250)

In [594]:
X_train_cvec.describe()

10         able        about      advance       advice  \
count  1318.000000  1318.000000  1318.000000  1318.000000  1318.000000   
mean      0.059181     0.043247     0.278452     0.043247     0.112291   
std       0.322980     0.309965     0.670910     0.217906     0.428113   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       0.000000     0.000000     0.000000     0.000000     0.000000   
max       5.000000     6.000000     6.000000     3.000000     5.000000   

             after      airport          all         also           am  \
count  1318.000000  1318.000000  1318.000000  1318.000000  1318.000000   
mean      0.072838     0.063733     0.225341     0.164643     0.235205   
std       0.351812     0.392262     0.639187     0.526642     0.759194   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       0.000000     0.000000     0.000000     0.000000     0.000000   
max       5.000000     7.000000    11.000000     6.000000     9.000000   

          ...              work        world        worth        would  \
count     ...       1318.000000  1318.000000  1318.000000  1318.000000   
mean      ...          0.069044     0.073596     0.049317     0.386950   
std       ...          0.360036     0.328200     0.296518     0.920803   
min       ...          0.000000     0.000000     0.000000     0.000000   
25%       ...          0.000000     0.000000     0.000000     0.000000   
50%       ...          0.000000     0.000000     0.000000     0.000000   
75%       ...          0.000000     0.000000     0.000000     0.000000   
max       ...          6.000000     4.000000     5.000000    13.000000   

               www        x200b         year        years          you  \
count  1318.000000  1318.000000  1318.000000  1318.000000  1318.000000   
mean      0.054628     0.207891     0.081942     0.052352     0.417299   
std       0.541425     0.938924     0.388864     0.269125     1.082927   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       0.000000     0.000000     0.000000     0.000000     0.000000   
max      13.000000    15.000000     6.000000     4.000000    19.000000   

              your  
count  1318.000000  
mean      0.104704  
std       0.494119  
min       0.000000  
25%       0.000000  
50%       0.000000  
75%       0.000000  
max       8.000000  

[8 rows x 250 columns]

In [595]:
# [i.count for i in X_train_cvec.columns if i!='']

In [596]:
nb=MultinomialNB() # instantiate the model

In [597]:
model_nb=nb.fit(X_train_cvec,y_train) # fit the model to counterized data

In [598]:
cross_val_score(model_nb,X_train_cvec,y_train,cv=5).mean()

0.8801037529321482

In [599]:
model_nb.score(X_train_cvec,y_train)

0.8846737481031867

In [600]:
model_nb.score(X_test_cvec,y_test)

0.6892307692307692

In [601]:
cm=confusion_matrix(y_test,model_nb.predict(X_test_cvec))
cm

array([[131, 190],
       [ 12, 317]])

In [602]:
round((cm[0][0]+cm[1][1])/cm.sum(),4)

0.6892

### b-Tf-IdfVectorizer

- best_paramaters <br>
{'vec__max_features': 1000,
 'vec__ngram_range': (1, 1),
 'vec__stop_words': 'english'}

In [603]:
tfvec=TfidfVectorizer(max_features=2000,
                     ngram_range=(1,2),
                     stop_words=None)

In [604]:
X_train_tfvec=pd.DataFrame(tfvec.fit_transform(X_train['merged']).todense(),columns=tfvec.get_feature_names())
X_test_tfvec=pd.DataFrame(tfvec.fit_transform(X_test['merged']).todense(),columns=tfvec.get_feature_names())

In [605]:
X_train_tfvec.shape

(1318, 2000)

In [606]:
X_test_tfvec.shape

(650, 2000)

In [607]:
cross_val_score(nb,X_train_tfvec,y_train,cv=3).mean()

0.8975702353834473

In [608]:
model_nb2=nb.fit(X_train_tfvec,y_train) # fit the model to data

In [609]:
model_nb2.score(X_train_tfvec,y_train)

0.9453717754172989

In [610]:
model_nb2.score(X_test_tfvec,y_test)

0.6

### c-hash

In [611]:
#  nb.fit(X_train_hvec,y_train) # after running --- 'Input X must be non-negative'

## 2- SVM

In [612]:
from sklearn import svm

In [613]:
model_svc=svm.SVC(C=1, kernel='linear')

### a-countvectorizer

- best_paramaters for kernel='rbf' <br>
{'vec__max_features': 250,
 'vec__ngram_range': (1, 1),
 'vec__stop_words': 'english'} <br>
- feeder: <br>
{'vec': CountVectorizer(analyzer='word', binary=False, decode_error='strict',
         dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
         lowercase=True, max_df=1.0, max_features=None, min_df=1,
         ngram_range=(1, 1), preprocessor=None, stop_words=None,
         strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
         tokenizer=None, vocabulary=None),
 'model': SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
   decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
   max_iter=-1, probability=False, random_state=None, shrinking=True,
   tol=0.001, verbose=False)}

- best_paramaters for kernel='linear' <br>
{'vec__max_features': None,
 'vec__ngram_range': (1, 1),
 'vec__stop_words': 'english'} <br>
- feeder :<BR>{'vec': CountVectorizer(analyzer='word', binary=False, decode_error='strict',
         dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
         lowercase=True, max_df=1.0, max_features=None, min_df=1,
         ngram_range=(1, 1), preprocessor=None, stop_words=None,
         strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
         tokenizer=None, vocabulary=None),
 'model': SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
   decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
   max_iter=-1, probability=False, random_state=None, shrinking=True,
   tol=0.001, verbose=False)}

- we need to convert data into number in order to apply SVM. So lets do countectorizing

In [614]:
cvec=CountVectorizer(max_features=250, stop_words='english')
X_train_cvec=cvec.fit_transform(X_train['merged'])
X_test_cvec=cvec.fit_transform(X_test['merged'])

# QUESTION TO INSTRUCTOR?
# when i want to apply the output of the Grid search it returned me error for 
# max_features=None. i think the problem is that the model firstly fits to X_train
# and model size is equal to X_train size(here is number of columns=9177 ). then i
# try to apply the model, which has same nummber of columns with X_train, to X_test 
# and it fails because size of X_test(columns=5643) doesnt match with size of model

In [615]:
# feature datas' format must be in array or matrix. if we wouldnt have matrix shape 
# so i would transform the shape into array as below code.
# pd.DataFrame(X_train_cvec.toarray(),columns=cvec.get_feature_names()) 

In [616]:
model_svc.fit(X_train_cvec,y_train)

SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [617]:
cross_val_score(model_svc,X_train_cvec,y_train,cv=5).mean()

0.8960387902266804

In [618]:
model_svc.score(X_train_cvec,y_train)

0.9468892261001517

In [619]:
model_svc.score(X_test_cvec,y_test)

0.8369230769230769

In [620]:
cm=confusion_matrix(y_test,model_svc.predict(X_test_cvec))
cm

array([[271,  50],
       [ 56, 273]])

### b- Tf-Idf

- best_paramaters for kernel='linear'<BR>
{'vec__max_features': 5000,
 'vec__ngram_range': (1, 1),
 'vec__stop_words': 'english'}

In [621]:
tfvec=TfidfVectorizer(max_features=245,
                     ngram_range=(1,1),
                     stop_words='english')

In [622]:
X_train_tfvec=pd.DataFrame(tfvec.fit_transform(X_train['merged']).todense(),columns=tfvec.get_feature_names())
X_test_tfvec=pd.DataFrame(tfvec.fit_transform(X_test['merged']).todense(),columns=tfvec.get_feature_names())

In [623]:
X_train_tfvec.shape

(1318, 245)

In [624]:
X_test_tfvec.shape

(650, 245)

In [625]:
model_svc.fit(X_train_tfvec,y_train)

SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [626]:
cross_val_score(model_svc,X_train_tfvec,y_train,cv=5).mean()

0.8975654638065859

In [627]:
model_svc.score(X_train_tfvec,y_train)

0.9317147192716236

In [628]:
model_svc.score(X_test_tfvec,y_test)

0.8015384615384615

### c- hash

In [629]:
hvec=HashingVectorizer(stop_words='english') # i used default value for n_features
X_train_hvec=hvec.fit_transform(X_train['merged'])
X_test_hvec=hvec.fit_transform(X_test['merged'])

In [630]:
X_train_hvec.shape

(1318, 1048576)

In [631]:
X_test_hvec.shape

(650, 1048576)

In [632]:
model_svc.fit(X_train_hvec,y_train)

SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [633]:
cross_val_score(model_svc,X_train_hvec,y_train,cv=5).mean()

0.9173114240185049

In [634]:
model_svc.score(X_train_hvec,y_train)

0.9863429438543247

In [635]:
model_svc.score(X_test_hvec,y_test)

0.9292307692307692

In [636]:
cm=confusion_matrix(y_test,model_svc.predict(X_test_hvec))
cm

array([[312,   9],
       [ 37, 292]])

## 3-LOGISTIC

In [637]:
from sklearn.linear_model import LogisticRegression

### a-countvectorizer

- best_paramaters <br>
{'vec__max_features': 5000,
 'vec__ngram_range': (1, 2),
 'vec__stop_words': 'english'}

In [638]:
model_log=LogisticRegression(penalty='l2') # 1- instantiate the model

In [639]:
# 2- prepare the X_train for fitting to the model. 
# a- firstly convert X_train and X_test from text to number, that is use any vector
# b- vector needs to fit and transfrom the text(so format of data must be series, matrix, array etc)

In [640]:
cvec=CountVectorizer(max_features=30,
                    tokenizer=None,
                token_pattern='(?u)\\b\\w\\w+\\b',
                    stop_words='english',
                    ngram_range=(1, 2))

In [641]:
X_train_cvec=pd.DataFrame(cvec.fit_transform(X_train['merged']).todense(),
                          columns=cvec.get_feature_names())
X_test_cvec=pd.DataFrame(cvec.fit_transform(X_test['merged']).todense(),
                          columns=cvec.get_feature_names())

In [642]:
model_log.fit(X_train_cvec,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [643]:
cross_val_score(model_log,X_train_cvec,y_train,cv=5).mean()

0.8482450264898791

In [644]:
model_log.score(X_train_cvec,y_train)

0.858877086494689

In [645]:
model_log.score(X_test_cvec,y_test)

0.7984615384615384

### b- Tf-Idf

- best_paramaters <br>
{'vec__max_features': 1000,
 'vec__ngram_range': (1, 1),
 'vec__stop_words': 'english'}

In [646]:
tfvec=TfidfVectorizer(max_features=25,
                     ngram_range=(1,1),
                     stop_words='english')

In [647]:
X_train_tfvec=pd.DataFrame(tfvec.fit_transform(X_train['merged']).todense(),
                           columns=tfvec.get_feature_names())
X_test_tfvec=pd.DataFrame(tfvec.fit_transform(X_test['merged']).todense(),
                          columns=tfvec.get_feature_names())

In [648]:
model_log.fit(X_train_tfvec,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [649]:
cross_val_score(model_log,X_train_tfvec,y_train,cv=5).mean()

0.8444456038975015

In [650]:
model_log.score(X_train_tfvec,y_train)

0.858877086494689

In [651]:
model_log.score(X_test_tfvec,y_test)

0.82

### c-hash

In [652]:
hvec=HashingVectorizer(stop_words='english')
X_train_hvec=hvec.fit_transform(X_train['merged'])
X_test_hvec=hvec.fit_transform(X_test['merged'])

In [653]:
X_train_hvec.shape

(1318, 1048576)

In [654]:
model_log.fit(X_train_hvec,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [655]:
cross_val_score(model_log,X_train_hvec,y_train,cv=5).mean()

0.8778195035946668

In [656]:
model_log.score(X_train_hvec,y_train)

0.9347496206373292

In [657]:
model_log.score(X_test_hvec,y_test)

0.9030769230769231

# SELECT THE BEST MODEL

- The _best score_ for test data is **SVM-hash**

In [658]:
predicts=model_svc.predict(X_test_hvec)
predicts[0:15]

array([0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1])

In [659]:
cm=confusion_matrix(y_test,predicts)
cm

array([[312,   9],
       [ 37, 292]])

In [673]:
pd.DataFrame(cm, columns=['predict - 0','predict - 1'],
             index=['actual - 0','actual - 1'])

predict - 0  predict - 1
actual - 0          312            9
actual - 1           37          292

In [674]:
y_test.value_counts()

1    329
0    321
Name: subreddit, dtype: int64

In [675]:
predicts.sum()

301